CREATE TABLE APPLICANTS (
    applicant_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    date_of_birth DATE NOT NULL,
    national_id_number VARCHAR2(20) UNIQUE NOT NULL,
    phone_number VARCHAR2(15) UNIQUE,
    email VARCHAR2(50) UNIQUE,
    residence_address VARCHAR2(200) NOT NULL,
    loan_status_check VARCHAR2(20) DEFAULT 'NEW'
);

CREATE INDEX idx_applicant_name ON APPLICANTS (last_name, first_name);
CREATE INDEX idx_applicant_name_2 ON APPLICANTS (last_name, first_name);

CREATE TABLE LOANS (
    loan_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id NUMBER(10) NOT NULL,
    loan_amount NUMBER(10, 2) NOT NULL,
    interest_rate NUMBER(5, 2) NOT NULL CHECK (interest_rate > 0),
    term_months NUMBER(3) NOT NULL CHECK (term_months > 0 AND term_months <= 60),
    disbursement_date DATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'DISBURSED', 'CLOSED')),
    CONSTRAINT fk_loan_applicant FOREIGN KEY (applicant_id)
        REFERENCES APPLICANTS (applicant_id) ON DELETE CASCADE
);

CREATE TABLE REPAYMENTS (
    repayment_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id NUMBER(10) NOT NULL,
    repayment_date DATE NOT NULL,
    payment_amount NUMBER(10, 2) NOT NULL CHECK (payment_amount > 0),
    payment_method VARCHAR2(50),
    CONSTRAINT fk_repayment_loan FOREIGN KEY (loan_id)
        REFERENCES LOANS (loan_id) ON DELETE CASCADE
);