-- ============================================
-- DATA RETRIEVAL QUERIES FOR MICROFINANCE MMS
-- ============================================

-- 1. BASIC LOAN INFORMATION QUERIES

-- Get all active loans with applicant details
SELECT 
    l.LOAN_ID,
    l.APPLICANT_ID,
    a.FIRST_NAME || ' ' || a.LAST_NAME AS APPLICANT_NAME,
    a.PHONE_NUMBER,
    a.EMAIL,
    l.LOAN_AMOUNT,
    l.INTEREST_RATE,
    l.TERM_MONTHS,
    l.DISBURSEMENT_DATE,
    l.STATUS,
    ADD_MONTHS(l.DISBURSEMENT_DATE, l.TERM_MONTHS) AS MATURITY_DATE
FROM LOANS l
JOIN APPLICANTS a ON l.APPLICANT_ID = a.APPLICANT_ID
WHERE l.STATUS = 'Active'
ORDER BY l.DISBURSEMENT_DATE DESC;

-- 2. LOAN REPAYMENT DETAILS

-- Get loan details with repayment summary
SELECT 
    l.LOAN_ID,
    l.APPLICANT_ID,
    l.LOAN_AMOUNT,
    l.INTEREST_RATE,
    l.TERM_MONTHS,
    l.STATUS,
    COUNT(r.REPAYMENT_ID) AS PAYMENTS_MADE,
    NVL(SUM(r.AMOUNT_PAID), 0) AS TOTAL_PAID,
    l.LOAN_AMOUNT - NVL(SUM(r.AMOUNT_PAID), 0) AS BALANCE_DUE,
    ROUND((NVL(SUM(r.AMOUNT_PAID), 0) / l.LOAN_AMOUNT) * 100, 2) AS PERCENT_PAID
FROM LOANS l
LEFT JOIN REPAYMENTS r ON l.LOAN_ID = r.LOAN_ID
GROUP BY l.LOAN_ID, l.APPLICANT_ID, l.LOAN_AMOUNT, l.INTEREST_RATE, 
         l.TERM_MONTHS, l.STATUS
ORDER BY PERCENT_PAID DESC;

-- 3. DETAILED REPAYMENT SCHEDULE FOR A SPECIFIC LOAN

-- Replace :loan_id with actual loan ID
SELECT 
    r.REPAYMENT_ID,
    r.REPAYMENT_DATE,
    r.AMOUNT_PAID,
    r.PRINCIPAL_AMOUNT,
    r.INTEREST_AMOUNT,
    r.STATUS,
    l.LOAN_AMOUNT,
    (SELECT SUM(AMOUNT_PAID) FROM REPAYMENTS WHERE LOAN_ID = l.LOAN_ID 
     AND REPAYMENT_DATE <= r.REPAYMENT_DATE) AS CUMULATIVE_PAID,
    l.LOAN_AMOUNT - (SELECT SUM(AMOUNT_PAID) FROM REPAYMENTS WHERE LOAN_ID = l.LOAN_ID 
     AND REPAYMENT_DATE <= r.REPAYMENT_DATE) AS REMAINING_BALANCE
FROM REPAYMENTS r
JOIN LOANS l ON r.LOAN_ID = l.LOAN_ID
WHERE r.LOAN_ID = :loan_id  -- Replace with actual loan ID
ORDER BY r.REPAYMENT_DATE;

-- 4. OVERDUE LOANS REPORT

SELECT 
    l.LOAN_ID,
    l.APPLICANT_ID,
    a.FIRST_NAME || ' ' || a.LAST_NAME AS APPLICANT_NAME,
    a.PHONE_NUMBER,
    l.LOAN_AMOUNT,
    l.DISBURSEMENT_DATE,
    ADD_MONTHS(l.DISBURSEMENT_DATE, l.TERM_MONTHS) AS MATURITY_DATE,
    l.STATUS,
    (SELECT MAX(REPAYMENT_DATE) FROM REPAYMENTS WHERE LOAN_ID = l.LOAN_ID) AS LAST_PAYMENT_DATE,
    SYSDATE - (SELECT MAX(REPAYMENT_DATE) FROM REPAYMENTS WHERE LOAN_ID = l.LOAN_ID) AS DAYS_SINCE_LAST_PAYMENT
FROM LOANS l
JOIN APPLICANTS a ON l.APPLICANT_ID = a.APPLICANT_ID
WHERE l.STATUS = 'Overdue'
   OR (l.STATUS = 'Active' 
       AND ADD_MONTHS(l.DISBURSEMENT_DATE, l.TERM_MONTHS) < SYSDATE)
ORDER BY DAYS_SINCE_LAST_PAYMENT DESC;

-- 5. LOANS BY STATUS

SELECT 
    STATUS,
    COUNT(*) AS LOAN_COUNT,
    SUM(LOAN_AMOUNT) AS TOTAL_AMOUNT,
    AVG(LOAN_AMOUNT) AS AVG_AMOUNT,
    MIN(LOAN_AMOUNT) AS MIN_AMOUNT,
    MAX(LOAN_AMOUNT) AS MAX_AMOUNT
FROM LOANS
GROUP BY STATUS
ORDER BY TOTAL_AMOUNT DESC;

-- 6. APPLICANT LOAN HISTORY

SELECT 
    a.APPLICANT_ID,
    a.FIRST_NAME || ' ' || a.LAST_NAME AS APPLICANT_NAME,
    a.JOINING_DATE,
    COUNT(l.LOAN_ID) AS TOTAL_LOANS,
    SUM(CASE WHEN l.STATUS = 'Active' THEN 1 ELSE 0 END) AS ACTIVE_LOANS,
    SUM(CASE WHEN l.STATUS = 'Paid Off' THEN 1 ELSE 0 END) AS PAID_LOANS,
    SUM(l.LOAN_AMOUNT) AS TOTAL_BORROWED,
    AVG(l.INTEREST_RATE) AS AVG_INTEREST_RATE
FROM APPLICANTS a
LEFT JOIN LOANS l ON a.APPLICANT_ID = l.APPLICANT_ID
GROUP BY a.APPLICANT_ID, a.FIRST_NAME, a.LAST_NAME, a.JOINING_DATE
HAVING COUNT(l.LOAN_ID) > 0
ORDER BY TOTAL_BORROWED DESC;

-- 7. MONTHLY DISBURSEMENT REPORT

SELECT 
    TO_CHAR(DISBURSEMENT_DATE, 'YYYY-MM') AS MONTH,
    COUNT(*) AS LOANS_DISBURSED,
    SUM(LOAN_AMOUNT) AS TOTAL_DISBURSED,
    AVG(LOAN_AMOUNT) AS AVG_LOAN_SIZE,
    AVG(INTEREST_RATE) AS AVG_INTEREST_RATE
FROM LOANS
GROUP BY TO_CHAR(DISBURSEMENT_DATE, 'YYYY-MM')
ORDER BY MONTH DESC;

-- 8. REPAYMENT HISTORY WITH DETAILS

SELECT 
    r.REPAYMENT_ID,
    r.LOAN_ID,
    l.APPLICANT_ID,
    a.FIRST_NAME || ' ' || a.LAST_NAME AS APPLICANT_NAME,
    r.REPAYMENT_DATE,
    r.AMOUNT_PAID,
    r.PRINCIPAL_AMOUNT,
    r.INTEREST_AMOUNT,
    r.STATUS,
    l.LOAN_AMOUNT,
    (SELECT SUM(AMOUNT_PAID) FROM REPAYMENTS r2 
     WHERE r2.LOAN_ID = l.LOAN_ID AND r2.REPAYMENT_DATE <= r.REPAYMENT_DATE) AS TOTAL_PAID_TO_DATE
FROM REPAYMENTS r
JOIN LOANS l ON r.LOAN_ID = l.LOAN_ID
JOIN APPLICANTS a ON l.APPLICANT_ID = a.APPLICANT_ID
WHERE r.REPAYMENT_DATE BETWEEN :start_date AND :end_date  -- Date range filter
ORDER BY r.REPAYMENT_DATE DESC;

-- 9. LOANS NEEDING ATTENTION (DUE SOON)

SELECT 
    l.LOAN_ID,
    l.APPLICANT_ID,
    a.FIRST_NAME || ' ' || a.LAST_NAME AS APPLICANT_NAME,
    l.LOAN_AMOUNT,
    l.DISBURSEMENT_DATE,
    ADD_MONTHS(l.DISBURSEMENT_DATE, l.TERM_MONTHS) AS MATURITY_DATE,
    l.STATUS,
    (SELECT SUM(AMOUNT_PAID) FROM REPAYMENTS WHERE LOAN_ID = l.LOAN_ID) AS TOTAL_PAID,
    l.LOAN_AMOUNT - (SELECT SUM(AMOUNT_PAID) FROM REPAYMENTS WHERE LOAN_ID = l.LOAN_ID) AS BALANCE_DUE
FROM LOANS l
JOIN APPLICANTS a ON l.APPLICANT_ID = a.APPLICANT_ID
WHERE l.STATUS = 'Active'
  AND ADD_MONTHS(l.DISBURSEMENT_DATE, l.TERM_MONTHS) BETWEEN SYSDATE AND SYSDATE + 30  -- Due in next 30 days
ORDER BY MATURITY_DATE;

-- 10. LOAN PERFORMANCE BY TERM

SELECT 
    CASE 
        WHEN TERM_MONTHS <= 12 THEN 'Short-term (≤1 year)'
        WHEN TERM_MONTHS <= 36 THEN 'Medium-term (1-3 years)'
        ELSE 'Long-term (>3 years)'
    END AS TERM_CATEGORY,
    COUNT(*) AS LOAN_COUNT,
    SUM(LOAN_AMOUNT) AS TOTAL_AMOUNT,
    AVG(INTEREST_RATE) AS AVG_INTEREST_RATE,
    SUM(CASE WHEN STATUS = 'Paid Off' THEN 1 ELSE 0 END) AS PAID_OFF_COUNT,
    SUM(CASE WHEN STATUS = 'Overdue' THEN 1 ELSE 0 END) AS OVERDUE_COUNT,
    ROUND((SUM(CASE WHEN STATUS = 'Paid Off' THEN 1 ELSE 0 END) / COUNT(*)) * 100, 2) AS SUCCESS_RATE
FROM LOANS
GROUP BY CASE 
    WHEN TERM_MONTHS <= 12 THEN 'Short-term (≤1 year)'
    WHEN TERM_MONTHS <= 36 THEN 'Medium-term (1-3 years)'
    ELSE 'Long-term (>3 years)'
END
ORDER BY TOTAL_AMOUNT DESC;